### ISSUE TITLE
Create `runVBN()` feature

### ISSUE THREAD

**Issue by chrishappy** [CMPT-479/CMPT-479-Project#23]

**Comment by chrishappy** [comment]
Some initial thoughts @brendansaw 

1. Driver launched the Program Under Test (PUT)
2. PUT outputs constraints + concrete values to an external datastore (e.g. a file)
3. Driver reads the external datastore (checks that the program went along the expected branch)
4. Checks if the program went along the expected branch; if not, restart with new random inputs
5. Stores the test case
6. Uses the constraints to generate another execution
7. Repeat until all the constraints have been negated.

**Comment by brendansaw** [comment]
Yep, this seems like the correct workflow for us to be implementing.
